branch-defaults:
  default:
    environment: prod
    group_suffix: null
  master:
    environment: prod-env
    group_suffix: null
environment-defaults:
  dev-enva:
    branch: null
    repository: null
global:
  application_name: Image Search Abstraction Layer
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
