branch-defaults:
  default:
    environment: dev-enva
    group_suffix: null
  master:
    environment: dev-enva
environment-defaults:
  dev-enva:
    branch: null
    repository: null
global:
  application_name: URL_Shortener_Microservice
  branch: null
  default_ec2_keyname: null
  default_platform: node.js
  default_region: us-west-2
  profile: eb-cli
  repository: null
  sc: git
