branch-defaults:
  master:
    environment: prod
    group_suffix: null
global:
  application_name: File_Metadata_Microservice
  branch: null
  default_ec2_keyname: AWS Key pair name
  default_platform: Node.js
  default_region: eu-central-1
  profile: eb-cli
  repository: null
  sc: git
